	websocketActorSystem {
	pekko {
		actor {
			provider = remote
			allow-java-serialization = on
			warn-about-java-serializer-usage = false
		}
		remote {
			artery {
				transport = tcp
				canonical {
					#private IP of this server
					hostname = "127.0.0.1"
					port = 2552
				}
				bind {
					hostname = "127.0.0.1"
					port = 2552
				}
	    	}
		}
	}
}

dev=true

mysqldb {
    host = "localhost:3306"
    schema = "airline"
    user = "mfc01"
    password = "ghEtmwBdnXYBQH4"
}

airline {
  local-lite = false
  actor {
    thread-pool-size = 8
  }
  db {
    pool {
      max-size = 100
    }
  }
  simulation {
    parallelism = 4
    log-timings = true
    memoize-routes = true
    demand {
      full-load-airports = true
    }
  }
}
